name: Publisher

on:
  push:
  schedule:
  - cron: 0 2 * * *

jobs:
  run:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm install
    - run: node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}