name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Security Scan
    uses: chrisns/.github/.github/workflows/security-scan.yml@main
